### ISSUE TITLE
Handle Siri launch

### ISSUE THREAD

**Issue by julienlibeau** [msepena/capacitor-plugin-sirishortcuts#2]
With tour example I can't handle "appLaunchBySirishortcuts" when I execute the shortcut.

I have this log from Xcode :
[Application] -[App.AppDelegate application:continueUserActivity:restorationHandler:] <NSUserActivity: 0x600001382080> has an interaction attached but it is not handled

Can you help ?

**Comment by mishelson** [comment]
hello I received the same error. I changed the repo and the listener worked. Now my problem is the donate of this new plugin https://www.npmjs.com/package/capacitor-plugin-siri-shorts
